# Generated by Django 2.2.1 on 2019-05-30 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_article_comment_likedislike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='LikeDislike',
        ),
    ]
